# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DogsChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DogsChat

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

pod 'Gallery'

pod 'NVActivityIndicatorView/AppExtension'
pod 'ProgressHUD'
pod 'SKPhotoBrowser'
pod 'Shuffle-iOS'

pod 'MessageKit'
pod 'InputBarAccessoryView'



end
